MNT: change jump host from pslogin to s3dflogin
pcdshub/shared-dotfiles pull request #65
Opened 2024-09-03 22:16 UTC by tangkong

Changes `pslogin` jump host to `s3dflogin`

Old AFS hosts will be decommissioned on Sept 30.  s3dflogin is the new recommended bastion jump host per Victor

2024-09-03 22:29 UTC, ZLLentz commented on off_site/ssh/config
>      HostName s3dflogin.slac.stanford.edu
nitpick: we have a duplicate `s3df` entry now, maybe this should become the main one above?

2024-09-03 22:31 UTC, tangkong commented on off_site/ssh/config
>      HostName s3dflogin.slac.stanford.edu
I deleted the proxy jump bit but not the rest of it hah

2024-09-03 22:56 UTC, ZLLentz approved these changes

2024-09-03 22:57 UTC, ZLLentz requested changes
one more, pslogin-arch line 16

2024-09-03 22:58 UTC, ZLLentz commented on off_site/ssh/config
>      #   which we set to "pslogin" here.
old comment
```suggestion
    #   which we set to "s3dflogin" here.
```

2024-09-04 00:21 UTC, ZLLentz commented on off_site/ssh/config
I can't quite reach it in the review, but there is still a reference to pslogin on lines 16 and 17- I should have been more clear earlier that I saw two misses, not one

2024-09-04 00:26 UTC, tangkong commented on off_site/ssh/config
I was admittedly not entirely sure if the archiver arch forwarding worked through s3dflogin, but it is reachable form s3dflogin so it should.

2024-09-04 16:22 UTC, ZLLentz commented on off_site/ssh/config
I had the same thought

2024-09-04 16:22 UTC, merged